---
- name: Temporary directory
  ansible.builtin.file:
    path: "{{ brew_install_tmp }}"
    state: directory
    mode: 0700
  become: false

- name: Download Homebrew install script
  ansible.builtin.get_url:
    url: "{{ brew_install_url }}"
    dest: "{{ brew_install_tmp }}/install.sh"
    checksum: "{{ brew_install_checksum | default(omit) }}"
    mode: 0700
  become: false

- name: Install Homebrew with the installer
  ansible.builtin.command: sh -c "{{ brew_install_tmp }}/install.sh"
  register: install_result
  changed_when: "install_result.rc == 0"
  become: false

- name: Ensure env set up
  ansible.builtin.shell:
    cmd: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ brew_install_tmp }}"
    state: absent
  become: false
