---
- name: Ensure Homebrew installed
  ansible.builtin.shell:
    cmd: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    creates: /home/linuxbrew
  register: homebrew_install

- name: Ensure env set up
  ansible.builtin.shell:
    cmd: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  when: homebrew_install.changed

- name: Install HomeBrew Packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_packages }}"


