---
- name: Ensure nvim folders present
  ansible.builtin.file:
    path: ~/.config/nvim/init.nvim
    state: directory

- name: Ensure nvim config up to date
  ansible.builtin.copy:
    src: config/nvim.init
    dest: ~/.config/nvim/init.nvim

- name: Ensure neovim plugins installed
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "~/.local/share/nvim/site/pack/plugins/start/{{ item.key }}"
  with_dict: "{{ neovim_plugins }}"
